<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Ajays-MacBook-Air.local" failures="1" tests="1" name="Default test" time="5.054" errors="0" timestamp="2021-09-29T16:12:51 IST">
  <testcase classname="com.testcases.LoginPageTest" name="validateMultipleLogin" time="1.81">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.testcases.LoginPageTest.validateMultipleLogin(java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateMultipleLogin([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) admin,(java.lang.String) admin123]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.testcases.LoginPageTest.validateMultipleLogin(java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateMultipleLogin([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) admin,(java.lang.String) admin123]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateMultipleLogin -->
  <testcase classname="com.testcases.LoginPageTest" name="validateTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- validateTitleTest -->
  <testcase classname="com.testcases.LoginPageTest" name="getDataFromTestNGXMLFile" time="0.0">
    <ignored/>
  </testcase> <!-- getDataFromTestNGXMLFile -->
  <testcase classname="com.testcases.LoginPageTest" name="validateLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- validateLoginTest -->
</testsuite> <!-- Default test -->
